### PR TITLE
Fixed suid problem on sailfish 2.1.0

### PR DESCRIPTION
**Pull request by Wedmer**
Also added Russian language.

### CODE REVIEW

**Comment by eatdust** [comment]
Would someone mind to build it for openrepos?
I think you have a few followers there loving this app :)
Thanks!

**Comment by fredldotme** [comment]
Didn't expect that, I'll set up the build environment, might have something ready over the weekend.

**Comment by Wedmer** [comment]
I can publish my build as release here on github.

**Comment by petRUShka** [comment]
Is there possibility to download package without compiling from sources?

**Comment by Wedmer** [comment]
There's release package at my fork page. Also I've published it at openrepos

**Comment by petRUShka** [comment]
@Wedmer could you please provide link to your openrepos?

**Comment by Wedmer** [comment]
https://openrepos.net/content/wedmer/isodrive-unofficial

**Pull request merged**
